name: OWASP ZAP Integration with GitHub Actions
on: [push]

jobs:
  zap_scan:
    runs-on: windows-latest
    name: Scan the web app
    
    # run-shell-command:
    # runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://gmail.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
     # - name: Echo a String
      #  run: echo "Hello DevSecOps Gurus!! This is my First GitHub Actions Workflow file"
